### PR TITLE
Pull repository current with teodorpatras/EasyTipView, Update for XCode 10.2 / Swift 5

### PR DESCRIPTION
**Pull request by John-Wolfe-Bose**
This pull request brings your master branch current with the master branch of the original source repository, as well as fixing an annoying warning on building the Sample App

This pull request also makes the code compile and work with XCode 10.2 and Swift 5.

I am John-Wolfe-Bose, and want to fix this code for further upstream projects.

### CODE REVIEW

**Comment by gokhanakkurt** [comment]
Hi John, 

Thanks for your contribution and effort 🍾  I'm going to merge your pull request.

**Comment by gokhanakkurt** [comment]
Hi John,

Thanks for your contribution and effort 🍾 I've merged your pull request.

**Comment by Mark-Collette** [comment]
Have you published the pod with the new podspec?

**Comment by gokhanakkurt** [comment]
> Have you published the pod with the new podspec?

Sorry for the late reply. Yes, @John-Wolfe-Bose had already updated the podspec file. Is there any issue w/ this?

**Pull request merged**
